services:
  ceramic:
    container_name: ceramic-one-mainnet
    environment:
      CERAMIC_ONE_NETWORK: "mainnet"
      CERAMIC_ONE_ETHEREUM_RPC_URLS: "https://reverse-proxy-prod.desci.com/rpc_mainnet"
      CERAMIC_ONE_EXTRA_CERAMIC_PEER_ADDRESSES: "/dns4/ceramic-one-prod.desci.com/tcp/4101/p2p/12D3KooWJx4BiKHSMXmJMvhdkhmKA8yG4jBC46ocWZGThsbXnx4C"
    volumes:
      - ../local-data/mainnet/ceramic-one:/data/ceramic-one
  codex-node:
    container_name: codex-node-mainnet
    environment:
      - CODEX_ENVIRONMENT=mainnet
    volumes:
      - ../local-data/mainnet/codex-node:/app/local-data/codex-node
